version: "3.3"

services:

  elasticseach:
    image: elasticsearch:7.4.2
    restart: always
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx1024m -Xms1024m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
#
#  kibana:
#    image: kibana:7.4.2
#    restart: always
#    container_name: kibana
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#    depends_on:
#      - elasticseach

  app:
    image: frankluxiao/gradle-spring-boot-elasticsearch
    container_name: gradle-spring-boot-elasticsearch
    ports:
      - 8080:8080
    links:
      - elasticseach
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar app.jar"
    depends_on:
      - elasticseach

volumes:
  esdata:
    driver: local
